require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # BACKEND_HOT_RELOAD=true reloads application code between requests. Off by default:
  # Docker Desktop does not deliver inotify across the bind mount, so the watcher has
  # to poll, and Solid Queue's poller threads sit outside the reloader interlock — which
  # is how `logging.failure` replaced every worker log line the last time this was left
  # on unconditionally.
  #
  # The worker process (`bin/jobs`) never reloads, even when the flag is on. Pick up a
  # job-code change with `./dev restart worker`.
  hot_reload = ActiveModel::Type::Boolean.new.cast(ENV.fetch("BACKEND_HOT_RELOAD", false)) &&
    File.basename($PROGRAM_NAME) != "jobs"

  config.enable_reloading = hot_reload

  # Docker Desktop virtiofs does not deliver inotify. FileUpdateChecker polls mtimes
  # between requests instead of depending on the listen gem.
  config.file_watcher = ActiveSupport::FileUpdateChecker if hot_reload

  # Load everything at boot when reloading is off, so a file that does not parse or a
  # missing constant fails the boot instead of the first request that hits it. When
  # reloading is on, eager load would fight the reloader.
  config.eager_load = !hot_reload

  # Runs on boot, and on each reload when BACKEND_HOT_RELOAD is on, so a rebuilt frontend
  # manifest is picked up without a server restart.
  config.to_prepare do
    FrontendAssets::Manifest.reset!
  end

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # WebSocket origins. Action Cable rejects any handshake whose Origin is not listed, and
  # the list is explicit even in development: a socket carrying the session cookie that
  # any page could open is the WebSocket equivalent of turning off CSRF protection.
  #
  # Both ports are here because the app is genuinely served from two: Rails renders the
  # HTML on BACKEND_PORT, and Vite serves modules from FRONTEND_PORT.
  config.action_cable.allowed_request_origins = [
    %r{\Ahttp://localhost:\d+\z},
    %r{\Ahttp://127\.0\.0\.1:\d+\z},
  ]

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
