require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Code is loaded once at boot and never reloaded. Pick up a change with:
  #
  #     ./dev restart backend worker
  #
  # This trades edit-to-effect latency for a dev process that behaves exactly like
  # production. What it buys:
  #
  #   * No file watcher. The polling watcher stat'd the whole autoload path on every
  #     request, which is the one reliable option across Docker Desktop's file sharing
  #     (inotify events do not cross it) and also the expensive one.
  #   * No reload interlock, and therefore no class of bug where a constant resolves on
  #     the request thread but raises NameError when first touched from a thread outside
  #     the interlock — which is exactly how Solid Queue's pollers silently replaced
  #     every worker log line with a `logging.failure` marker.
  #   * No half-reloaded state, where a renamed constant or an edited initializer leaves
  #     the process disagreeing with the source on disk.
  config.enable_reloading = false

  # Load everything at boot, which is the consistent pairing with reloading disabled: no
  # lazy autoloading happens later from an arbitrary thread, and a file that does not
  # parse or a missing constant fails the boot instead of the first request that hits it.
  config.eager_load = true

  # Runs once at boot now that reloading is off. Kept so that development running against
  # a built frontend resolves the manifest from a clean state.
  config.to_prepare do
    FrontendAssets::Manifest.reset!
  end

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
